title: Trent Kindvall # your name (or website title) here
logo: <img src="/Images/Headshot.jpg" style="eight: 100px; width:100px;"/>
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/trent-kindvall/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-SPE7WS1TL3 # your Google Analytics tracking ID here
